language: c

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libqrencode-dev
  - wget http://security.ubuntu.com/ubuntu/pool/main/g/gpgme1.0/libgpgme-dev_1.8.0-3ubuntu5_i386.deb
  - sudo gdebi libgpgme-dev_1.8.0-3ubuntu5_i386.deb

script:
  - make
